import type { Metadata } from "next";
import NavLayout from "@/components/common/navigation/nav-layout";
import "../../../app/globals.css"
import { Toaster } from "sonner";
export const metadata: Metadata = {
    title: "Create all kinds of products",
    description: "Generated by Nehemiah Products",
};

export default function RootLayouts({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <NavLayout>
            {children}
        </NavLayout>
    );
}
